| Generated by generate.py from playmode.c, adapter.c and hooks.s.
| Edit those; run `python3 generate.py` to refresh this file.

| ---- playmode.c + adapter.c ----
#NO_APP
	.file	"playmodes_unit.c"
	.text
	.align	2
	.type	pm_nv_row, @function
pm_nv_row:
	lea (-20,%sp),%sp
	movem.l #124,(%sp)
	move.l 24(%sp),%d0
	move.l %d0,%d5
	lsl.l #4,%d5
	move.l %d0,%d1
	mov3q.l #1,%d6
	lsl.l #3,%d1
	move.b 269455108,%d3
	mvz.b 269455109,%d2
	add.l %d0,%d5
	move.l %d5,%a0
	add.l #pm_table,%a0
	move.l %d1,%a1
	add.l %d0,%a1
	add.l #269452804,%a1
	add.l #pm_table+18,%d5
	sub.l %a0,%d6
	lsl.l #8,%d3
	or.l %d2,%d3
.L4:
	move.l %d6,%d1
	moveq #17,%d2
	move.b (%a0),%d0
	add.l %a0,%d1
	cmp.l %d1,%d2
	jeq .L5
	move.b 1(%a0),%d2
	moveq #15,%d1
	and.l %d1,%d2
.L2:
	lsl.l #4,%d0
	mvz.b (%a1),%d1
	move.l %d3,%d4
	addq.l #2,%a0
	sub.l %d1,%d4
	or.l %d2,%d0
	mvz.b %d0,%d2
	cmp.l %d1,%d2
	jeq .L3
	move.b %d0,(%a1)
	move.l %d2,%d3
	add.l %d4,%d3
.L3:
	addq.l #1,%a1
	cmp.l %d5,%a0
	jne .L4
	mvz.w %d3,%d3
	move.l %d3,%d0
	lsr.l #8,%d0
	move.b %d0,269455108
	move.b %d3,269455109
	movem.l (%sp),#124
	lea (20,%sp),%sp
	rts
.L5:
	clr.b %d2
	jra .L2
	.size	pm_nv_row, .-pm_nv_row
	.align	2
	.type	pm_store_current, @function
pm_store_current:
	move.l %a2,-(%sp)
	move.l %d2,-(%sp)
	move.w pm_cur,%d2
	jeq .L9
	move.l %d2,%d1
	subq.l #1,%d1
	mulu.w #17,%d1
	lea pm_state,%a1
	mov3q.l #1,%d0
	move.l %d1,%a0
	add.l #pm_table,%a0
	move.b (%a1),(%a0)
.L11:
	lea (%a1,%d0.l),%a2
	moveq #17,%d1
	move.b (%a2),(%a0,%d0.l)
	addq.l #1,%d0
	cmp.l %d0,%d1
	jne .L11
	mvz.w %d2,%d2
	move.l %d2,%a0
	pea -1(%a0)
	jsr pm_nv_row
	addq.l #4,%sp
.L9:
	move.l (%sp)+,%d2
	move.l (%sp)+,%a2
	rts
	.size	pm_store_current, .-pm_store_current
	.align	2
	.type	pattern_row, @function
pattern_row:
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	move.l 12(%sp),%d0
	cmp.l #1175224610,%d0
	jeq .L22
	cmp.l #1175187992,%d0
	jeq .L23
	cmp.l #1074667999,%d0
	jls .L21
	add.l #-1074668000,%d0
	cmp.l #10171391,%d0
	jhi .L21
	move.l #635712,%d2
	remu.l %d2,%d1:%d0
	divu.l %d2,%d0
	cmp.l #585087,%d1
	jhi .L21
	mvz.w #36568,%d3
	remu.l %d3,%d2:%d1
	divu.l %d3,%d1
	tst.l %d2
	jne .L21
	lsl.l #4,%d0
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	add.l %d1,%d0
	mulu.w #17,%d0
	add.l #pm_table,%d0
	rts
.L21:
	move.l (%sp)+,%d2
	clr.l %d0
	move.l (%sp)+,%d3
	rts
.L22:
	move.l (%sp)+,%d2
	move.l #pm_clip,%d0
	move.l (%sp)+,%d3
	rts
.L23:
	move.l (%sp)+,%d2
	move.l #pm_undo,%d0
	move.l (%sp)+,%d3
	rts
	.size	pattern_row, .-pattern_row
	.align	2
	.type	pm_map.part.0, @function
pm_map.part.0:
	lea (-32,%sp),%sp
	move.l 40(%sp),%a1
	move.l %a1,%a0
	movem.l #252,(%sp)
	move.l 36(%sp),%d0
	moveq #64,%d2
	move.l 48(%sp),%d1
	cmp.l %a1,%d2
	jcc .L27
	move.w #64,%a0
.L27:
	cmp.l %a0,%d1
	jcs .L28
	move.l %a0,%d3
	remu.l %d3,%d2:%d1
	divu.l %d3,%d1
	add.l %d1,44(%sp)
	move.l %d2,%d1
.L28:
	mov3q.l #3,%d4
	cmp.l %d0,%d4
	jeq .L29
	jcc .L52
	mov3q.l #4,%d2
	cmp.l %d0,%d2
	jeq .L34
	subq.l #5,%d0
	tst.l %d0
	jne .L36
	mvz.w %a0,%d2
	move.l 44(%sp),%d3
	move.w %a0,%d7
	add.l %d2,%d2
	remu.l %d2,%d0:%d3
	mulu.w %d7,%d0
	add.l %d0,%d1
	remu.l %d2,%d0:%d1
	cmp.l %a0,%d0
	jcs .L26
	subq.l #1,%d2
	sub.l %d0,%d2
	move.l %d2,%d0
.L26:
	movem.l (%sp),#252
	lea (32,%sp),%sp
	rts
.L52:
	mov3q.l #1,%d6
	cmp.l %d0,%d6
	jeq .L31
	subq.l #2,%d0
	tst.l %d0
	jne .L36
	mov3q.l #1,%d4
	cmp.l %a1,%d4
	jeq .L43
	move.l %a0,%d2
	subq.l #1,%d2
	mvz.w %d2,%d2
	move.l 44(%sp),%d3
	move.w %a0,%d6
	add.l %d2,%d2
	remu.l %d2,%d0:%d3
	mulu.w %d6,%d0
	add.l %d0,%d1
	remu.l %d2,%d0:%d1
	cmp.l %a0,%d0
	jcs .L26
	sub.l %d0,%d2
	move.l %d2,%d0
	jra .L26
.L36:
	movem.l (%sp),#252
	move.l %d1,%d0
	lea (32,%sp),%sp
	rts
.L31:
	movem.l (%sp),#252
	move.l %a0,%d0
	subq.l #1,%d0
	sub.l %d1,%d0
	lea (32,%sp),%sp
	rts
.L34:
	mov3q.l #1,%d0
	cmp.l %a1,%d0
	jcc .L43
	sub.l %a1,%a1
.L39:
	addq.l #1,%a1
	move.l %d0,%d3
	move.l %a1,%d2
	lsl.l %d2,%d3
	cmp.l %a0,%d3
	jcs .L39
	tst.l %a1
	jeq .L43
	move.l 44(%sp),%d2
	move.l #668265263,%d4
	move.l %d1,%d0
	move.l #2146121005,%d7
	move.l 52(%sp),%d1
	move.l %a1,%d6
	muls.l %d4,%d2
	moveq #15,%d4
	lsr.l #1,%d6
	subq.l #1,%d3
	move.l %d6,28(%sp)
	move.l #-2073254261,%d6
	eor.l %d2,%d1
	move.l %d1,%d2
	clr.w %d2
	swap %d2
	eor.l %d2,%d1
	muls.l %d7,%d1
	mov3q.l #1,%d7
	move.l %d1,%d2
	lsr.l %d4,%d2
	eor.l %d2,%d1
	muls.l %d6,%d1
	move.l %d1,%d2
	clr.w %d2
	swap %d2
	eor.l %d2,%d1
	move.l %d1,%d5
	add.l #-626627285,%d5
	move.l %d1,24(%sp)
	cmp.l %a1,%d7
	jeq .L44
.L53:
	move.l 28(%sp),%d4
	move.l 24(%sp),%d2
.L41:
	move.l %d2,%d1
	move.l #2146121005,%d6
	clr.w %d1
	swap %d1
	moveq #15,%d7
	eor.l %d2,%d1
	add.l #-1640531527,%d2
	muls.l %d6,%d1
	move.l %d1,%d6
	lsr.l %d7,%d6
	mov3q.l #1,%d7
	eor.l %d6,%d1
	move.l #-2073254261,%d6
	muls.l %d6,%d1
	move.l %d1,%d6
	clr.w %d6
	swap %d6
	eor.l %d6,%d1
	move.l %d1,%d6
	lsr.l #8,%d1
	add.l %d6,%d6
	or.l %d7,%d6
	muls.l %d0,%d6
	add.l %d6,%d1
	and.l %d3,%d1
	move.l %d1,%d0
	lsr.l %d4,%d0
	eor.l %d1,%d0
	cmp.l %d5,%d2
	jne .L41
	and.l %d3,%d0
	cmp.l %a0,%d0
	jcs .L26
	mov3q.l #1,%d7
	cmp.l %a1,%d7
	jne .L53
.L44:
	move.l 24(%sp),%d2
	mov3q.l #1,%d4
	jra .L41
.L29:
	move.l 44(%sp),%d0
	move.l #-2048144789,%d2
	move.l #-1028477387,%d3
	muls.l %d3,%d1
	muls.l %d2,%d0
	moveq #15,%d2
	move.l #-2073254261,%d3
	move.l 52(%sp),%d4
	move.l #2146121005,%d6
	move.w %a0,%d7
	move.l %d0,%a1
	lea 1(%a1,%d1.l),%a1
	move.l %a1,%d0
	move.l %a1,%d1
	clr.w %d0
	swap %d0
	eor.l %d1,%d0
	move.l #2146121005,%d1
	muls.l %d1,%d0
	move.l %d0,%d1
	lsr.l %d2,%d1
	eor.l %d1,%d0
	muls.l %d3,%d0
	move.l %d0,%d1
	eor.l %d4,%d0
	clr.w %d1
	swap %d1
	eor.l %d0,%d1
	move.l %d1,%d0
	clr.w %d0
	swap %d0
	eor.l %d1,%d0
	muls.l %d6,%d0
	move.l %d0,%d1
	lsr.l %d2,%d1
	eor.l %d1,%d0
	muls.l %d3,%d0
	clr.w %d0
	swap %d0
	mulu.w %d7,%d0
	movem.l (%sp),#252
	clr.w %d0
	swap %d0
	lea (32,%sp),%sp
	rts
.L43:
	movem.l (%sp),#252
	clr.l %d0
	lea (32,%sp),%sp
	rts
	.size	pm_map.part.0, .-pm_map.part.0
	.align	2
	.type	run_seed.isra.0, @function
run_seed.isra.0:
	move.l %d2,-(%sp)
	move.l #-2048144789,%d0
	move.l 16(%sp),%d1
	move.l #-1640531527,%d2
	muls.l %d0,%d1
	move.l 12(%sp),%d0
	muls.l %d2,%d0
	moveq #15,%d2
	move.l %d1,%a0
	lea 1(%a0,%d0.l),%a0
	move.l %a0,%d0
	move.l %a0,%d1
	clr.w %d0
	swap %d0
	eor.l %d1,%d0
	move.l #2146121005,%d1
	muls.l %d1,%d0
	move.l %d0,%d1
	lsr.l %d2,%d1
	move.l #2146121005,%d2
	eor.l %d1,%d0
	move.l #-2073254261,%d1
	muls.l %d1,%d0
	move.l 8(%sp),%d1
	eor.l %d0,%d1
	clr.w %d0
	swap %d0
	eor.l %d0,%d1
	move.l %d1,%d0
	clr.w %d0
	swap %d0
	eor.l %d1,%d0
	muls.l %d2,%d0
	moveq #15,%d2
	move.l %d0,%d1
	lsr.l %d2,%d1
	move.l (%sp)+,%d2
	eor.l %d1,%d0
	move.l #-2073254261,%d1
	muls.l %d1,%d0
	move.l %d0,%d1
	clr.w %d1
	swap %d1
	eor.l %d1,%d0
	rts
	.size	run_seed.isra.0, .-run_seed.isra.0
	.align	2
	.type	pm_lookup_next_run.part.0, @function
pm_lookup_next_run.part.0:
	lea (-20,%sp),%sp
	movem.l #1036,(%sp)
	move.l 24(%sp),%a2
	move.l 28(%sp),%a0
	move.l 36(%sp),%d2
	move.l 216(%a2),%d1
	addq.l #1,%d1
	move.l 212(%a2),%d0
	move.l 32(%sp),16(%sp)
	tst.l 40(%sp)
	jeq .L66
	move.l %a0,-(%sp)
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	move.l %a0,24(%sp)
	jsr (run_seed.isra.0)
	lea (12,%sp),%sp
	move.l 12(%sp),%a0
	move.b 1(%a2,%a0.l),%d1
.L61:
	mvz.b %d1,%d1
	mov3q.l #5,%d3
	cmp.l %d1,%d3
	jcc .L59
	clr.l %d1
.L59:
	tst.l %d2
	jeq .L62
	move.l %d2,28(%sp)
	movem.l (%sp),#1036
	move.l %d0,40(%sp)
	move.l 16(%sp),36(%sp)
	clr.l 32(%sp)
	move.l %d1,24(%sp)
	lea (20,%sp),%sp
	jra (pm_map.part.0)
.L66:
	clr.l -(%sp)
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	jsr (run_seed.isra.0)
	lea (12,%sp),%sp
	move.b (%a2),%d1
	jra .L61
.L62:
	movem.l (%sp),#1036
	clr.l %d0
	lea (20,%sp),%sp
	rts
	.size	pm_lookup_next_run.part.0, .-pm_lookup_next_run.part.0
	.align	2
	.type	pm_nv_store, @function
pm_nv_store:
	lea (-24,%sp),%sp
	movem.l #252,(%sp)
	move.l #pm_table,%d6
	clr.l %d2
	move.l #pm_table+18,%d4
	move.l #269452804,%d7
.L68:
	mov3q.l #1,%d5
	move.l %d7,%a1
	move.l %d6,%a0
	sub.l %d6,%d5
.L71:
	move.l %d5,%d1
	moveq #17,%d3
	move.b (%a0),%d0
	add.l %a0,%d1
	cmp.l %d1,%d3
	jeq .L73
	move.b 1(%a0),%d1
	moveq #15,%d3
	and.l %d3,%d1
.L69:
	lsl.l #4,%d0
	mvz.b (%a1),%d3
	addq.l #2,%a0
	or.l %d1,%d0
	mvz.b %d0,%d1
	add.l %d1,%d2
	cmp.l %d3,%d1
	jeq .L70
	move.b %d0,(%a1)
.L70:
	addq.l #1,%a1
	cmp.l %d4,%a0
	jne .L71
	add.l #17,%d4
	add.l #17,%d6
	add.l #9,%d7
	cmp.l #pm_table+4370,%d4
	jne .L68
	mvz.w %d2,%d2
	moveq #77,%d3
	move.l %d2,%d0
	lsr.l #8,%d0
	move.b %d0,269455108
	moveq #80,%d0
	move.b %d2,269455109
	move.b %d0,269452800
	move.b %d3,269452801
	moveq #78,%d0
	moveq #86,%d3
	move.b %d0,269452802
	move.b %d3,269452803
	movem.l (%sp),#252
	lea (24,%sp),%sp
	rts
.L73:
	clr.b %d1
	jra .L69
	.size	pm_nv_store, .-pm_nv_store
	.align	2
	.globl	pm_map
	.type	pm_map, @function
pm_map:
	move.l 8(%sp),%d0
	move.l 4(%sp),%d1
	move.l 12(%sp),%a0
	tst.l %d0
	jeq .L78
	move.l %a0,12(%sp)
	move.l %d0,8(%sp)
	move.l %d1,4(%sp)
	jra (pm_map.part.0)
.L78:
	rts
	.size	pm_map, .-pm_map
	.align	2
	.globl	pm_mode
	.type	pm_mode, @function
pm_mode:
	move.l 4(%sp),%a0
	tst.l 12(%sp)
	jeq .L82
	moveq #15,%d0
	cmp.l 8(%sp),%d0
	jcs .L82
	move.l 8(%sp),%d1
	mvz.b 1(%a0,%d1.l),%d0
.L83:
	mov3q.l #5,%d1
	cmp.l %d0,%d1
	jcc .L81
	clr.l %d0
.L81:
	rts
.L82:
	mvz.b (%a0),%d0
	jra .L83
	.size	pm_mode, .-pm_mode
	.align	2
	.globl	pm_reset
	.type	pm_reset, @function
pm_reset:
	move.l %a2,-(%sp)
	moveq #15,%d1
	move.l %d2,-(%sp)
	move.l 16(%sp),%d0
	move.l 12(%sp),%a0
	cmp.l %d0,%d1
	jcs .L90
	moveq #12,%d1
	muls.l %d0,%d1
	move.l #-2048144789,%d2
	muls.l %d2,%d0
	clr.w %d2
	lea (%a0,%d1.l),%a1
	clr.l 20(%a1)
	move.w %d2,28(%a0,%d1.l)
	move.l #-1640531527,%d2
	move.l 216(%a0),%d1
	muls.l %d2,%d1
	moveq #15,%d2
	move.l %d1,%a2
	lea 1(%a2,%d0.l),%a2
	move.l %a2,%d0
	move.l %a2,%d1
	clr.w %d0
	swap %d0
	eor.l %d1,%d0
	move.l #2146121005,%d1
	muls.l %d1,%d0
	move.l %d0,%d1
	lsr.l %d2,%d1
	move.l #2146121005,%d2
	eor.l %d1,%d0
	move.l #-2073254261,%d1
	muls.l %d1,%d0
	move.l 212(%a0),%d1
	eor.l %d0,%d1
	clr.w %d0
	swap %d0
	eor.l %d0,%d1
	move.l %d1,%d0
	clr.w %d0
	swap %d0
	eor.l %d1,%d0
	muls.l %d2,%d0
	moveq #15,%d2
	move.l %d0,%d1
	lsr.l %d2,%d1
	eor.l %d1,%d0
	move.l #-2073254261,%d1
	muls.l %d1,%d0
	move.l %d0,%d1
	clr.w %d1
	swap %d1
	eor.l %d1,%d0
	move.l %d0,24(%a1)
.L90:
	move.l (%sp)+,%d2
	move.l (%sp)+,%a2
	rts
	.size	pm_reset, .-pm_reset
	.align	2
	.globl	pm_reset_all
	.type	pm_reset_all, @function
pm_reset_all:
	lea (-12,%sp),%sp
	move.l 16(%sp),%a1
	move.l #-1640531527,%d1
	movem.l #28,(%sp)
	move.l 216(%a1),%d0
	addq.l #1,%d0
	muls.l %d0,%d1
	move.l 212(%a1),%d2
	lea (20,%a1),%a0
	lea (212,%a1),%a1
	move.l %d0,4(%a1)
	addq.l #1,%d1
.L95:
	move.l %d1,%d0
	move.l #2146121005,%d4
	clr.w %d0
	swap %d0
	clr.l (%a0)
	clr.w %d3
	lea (12,%a0),%a0
	eor.l %d1,%d0
	add.l #-2048144789,%d1
	move.w %d3,-4(%a0)
	muls.l %d4,%d0
	moveq #15,%d4
	move.l %d0,%d3
	lsr.l %d4,%d3
	move.l #2146121005,%d4
	eor.l %d3,%d0
	move.l #-2073254261,%d3
	muls.l %d3,%d0
	move.l %d2,%d3
	eor.l %d0,%d3
	clr.w %d0
	swap %d0
	eor.l %d0,%d3
	move.l %d3,%d0
	clr.w %d0
	swap %d0
	eor.l %d3,%d0
	muls.l %d4,%d0
	moveq #15,%d4
	move.l %d0,%d3
	lsr.l %d4,%d3
	eor.l %d3,%d0
	move.l #-2073254261,%d3
	muls.l %d3,%d0
	move.l %d0,%d3
	clr.w %d3
	swap %d3
	eor.l %d3,%d0
	move.l %d0,-8(%a0)
	cmp.l %a0,%a1
	jne .L95
	movem.l (%sp),#28
	lea (12,%sp),%sp
	rts
	.size	pm_reset_all, .-pm_reset_all
	.align	2
	.globl	pm_init
	.type	pm_init, @function
pm_init:
	move.l 8(%sp),%d1
	move.l 4(%sp),%a1
	move.l %a1,%d0
	move.l %a1,%a0
	add.l #220,%d0
.L100:
	clr.b (%a0)+
	cmp.l %a0,%d0
	jne .L100
	tst.l %d1
	jne .L101
	move.l #1831565813,%d1
.L101:
	move.l %d1,212(%a1)
	move.l %a1,4(%sp)
	jra pm_reset_all
	.size	pm_init, .-pm_init
	.align	2
	.type	pm_ensure, @function
pm_ensure:
	lea (-12,%sp),%sp
	movem.l #1036,(%sp)
	tst.b pm_ready.l
	jeq .L133
	move.b -2147457603,%d0
	move.b -2147457602,%d1
	moveq #15,%d3
	move.l %d0,%d2
	or.l %d1,%d2
	mvz.b %d2,%d2
	cmp.l %d2,%d3
	jcs .L106
	mvz.b %d0,%d0
	mvz.b %d1,%d1
	mvz.w pm_cur,%d2
	lsl.l #4,%d0
	move.l %d2,%a0
	add.l %d0,%d1
	move.l %d1,%d2
	addq.l #1,%d2
	cmp.l %a0,%d2
	jeq .L106
	mulu.w #17,%d1
	lea pm_state,%a2
	mov3q.l #1,%d0
	lea pm_state+1,%a1
	move.l %d1,%a0
	add.l #pm_table,%a0
	move.b (%a0),(%a2)
.L121:
	move.b (%a0,%d0.l),(%a1)+
	addq.l #1,%d0
	moveq #17,%d3
	cmp.l %d0,%d3
	jne .L121
	move.w %d2,pm_cur
.L106:
	movem.l (%sp),#1036
	lea (12,%sp),%sp
	rts
.L133:
	move.l 1175473392,%d0
	lea pm_state,%a2
	move.l %a2,%a0
.L108:
	clr.b (%a0)+
	cmp.l #pm_state+220,%a0
	jne .L108
	tst.l %d0
	jeq .L134
	move.l %a2,-(%sp)
	move.l %d0,pm_state+212
	jsr pm_reset_all
	addq.l #4,%sp
	lea pm_table,%a1
	move.l #pm_table+17,%d0
	move.l #pm_table+4369,%d1
.L110:
	move.l %d0,%a0
	lea (-17,%a0),%a0
.L111:
	clr.b (%a0)+
	cmp.l %d0,%a0
	jne .L111
	add.l #17,%d0
	cmp.l %d1,%d0
	jne .L110
	mvz.b 269452800,%d0
	moveq #80,%d1
	cmp.l %d0,%d1
	jne .L113
	mvz.b 269452801,%d0
	moveq #77,%d2
	cmp.l %d0,%d2
	jne .L113
	mvz.b 269452802,%d0
	moveq #78,%d3
	cmp.l %d0,%d3
	jne .L113
	mvz.b 269452803,%d0
	moveq #86,%d1
	cmp.l %d0,%d1
	jne .L113
	move.l #269452804,%a0
	clr.l %d0
.L114:
	mvz.b (%a0)+,%d1
	add.l %d1,%d0
	cmp.l #269455108,%a0
	jne .L114
	move.b (%a0),%d1
	mvz.b 269455109,%d2
	mvz.w %d0,%d0
	mvz.b %d1,%d1
	lsl.l #8,%d1
	or.l %d2,%d1
	cmp.l %d0,%d1
	jne .L113
	move.l #269452804,%a0
.L117:
	clr.l %d1
.L116:
	move.l %d1,%d2
	not.l %d2
	lsl.l #2,%d2
	mov3q.l #4,%d3
	move.l %d1,%d0
	lsr.l #1,%d0
	mvz.b (%a0,%d0.l),%d0
	and.l %d3,%d2
	mov3q.l #5,%d3
	asr.l %d2,%d0
	moveq #15,%d2
	and.l %d2,%d0
	cmp.l %d0,%d3
	jge .L115
	clr.l %d0
.L115:
	move.b %d0,(%a1,%d1.l)
	addq.l #1,%d1
	moveq #17,%d0
	cmp.l %d1,%d0
	jne .L116
	lea (17,%a1),%a1
	lea (9,%a0),%a0
	cmp.l #pm_table+4352,%a1
	jne .L117
.L118:
	clr.w %d1
	moveq #1,%d2
	moveq #15,%d3
	move.w %d1,pm_cur
	move.b %d2,pm_ready
	move.b -2147457603,%d0
	move.b -2147457602,%d1
	move.l %d1,%d2
	or.l %d0,%d2
	mvz.b %d2,%d2
	cmp.l %d2,%d3
	jcs .L106
	mvz.b %d0,%d0
	mvz.b %d1,%d1
	lea pm_state+1,%a1
	lsl.l #4,%d0
	add.l %d0,%d1
	move.l %d1,%d2
	mov3q.l #1,%d0
	mulu.w #17,%d1
	addq.l #1,%d2
	move.l %d1,%a0
	add.l #pm_table,%a0
	move.b (%a0),(%a2)
	jra .L121
.L134:
	move.l #1831565813,%d0
	move.l %a2,-(%sp)
	move.l %d0,pm_state+212
	jsr pm_reset_all
	addq.l #4,%sp
	lea pm_table,%a1
	move.l #pm_table+17,%d0
	move.l #pm_table+4369,%d1
	jra .L110
.L113:
	jsr pm_nv_store
	jra .L118
	.size	pm_ensure, .-pm_ensure
	.align	2
	.globl	pm_lookup_next_run
	.type	pm_lookup_next_run, @function
pm_lookup_next_run:
	lea (-16,%sp),%sp
	moveq #15,%d0
	move.l %d2,-(%sp)
	move.l 28(%sp),%d1
	move.l 24(%sp),%a0
	move.l 32(%sp),16(%sp)
	move.l 36(%sp),12(%sp)
	cmp.l %d1,%d0
	jcs .L141
	move.l 216(%a0),%a1
	addq.l #1,%a1
	move.l 212(%a0),%d0
	tst.l 40(%sp)
	jeq .L146
	move.l %d1,-(%sp)
	move.l %a1,-(%sp)
	move.l %d0,-(%sp)
	move.l %d1,20(%sp)
	move.l %a0,16(%sp)
	jsr (run_seed.isra.0)
	lea (12,%sp),%sp
	move.l 8(%sp),%d1
	move.l 4(%sp),%a0
	move.b 1(%a0,%d1.l),%d1
.L140:
	mvz.b %d1,%d1
	mov3q.l #5,%d2
	cmp.l %d1,%d2
	jcc .L139
	clr.l %d1
.L139:
	tst.l 12(%sp)
	jeq .L142
	move.l %d0,40(%sp)
	move.l 16(%sp),36(%sp)
	clr.l 32(%sp)
	move.l 12(%sp),28(%sp)
	move.l %d1,24(%sp)
	move.l (%sp)+,%d2
	lea (16,%sp),%sp
	jra (pm_map.part.0)
.L146:
	clr.l -(%sp)
	move.l %a1,-(%sp)
	move.l %d0,-(%sp)
	move.l %a0,16(%sp)
	jsr (run_seed.isra.0)
	lea (12,%sp),%sp
	move.l 4(%sp),%a0
	move.b (%a0),%d1
	jra .L140
.L141:
	move.l 16(%sp),%d0
	move.l (%sp)+,%d2
	lea (16,%sp),%sp
	rts
.L142:
	move.l (%sp)+,%d2
	clr.l %d0
	lea (16,%sp),%sp
	rts
	.size	pm_lookup_next_run, .-pm_lookup_next_run
	.align	2
	.globl	pm_advance
	.type	pm_advance, @function
pm_advance:
	lea (-12,%sp),%sp
	move.l 20(%sp),%d0
	movem.l #28,(%sp)
	move.l 24(%sp),%d1
	moveq #15,%d2
	cmp.l %d0,%d2
	jcs .L147
	tst.l 28(%sp)
	jeq .L150
	cmp.l 28(%sp),%d1
	jcs .L150
	move.l 28(%sp),%d4
	move.l %d1,%d3
	remu.l %d4,%d2:%d3
	move.l %d2,%d1
.L150:
	moveq #12,%d3
	muls.l %d3,%d0
	move.l 16(%sp),%a0
	add.l %d0,%a0
	tst.b 29(%a0)
	jeq .L156
	mvz.b 28(%a0),%d2
	cmp.l %d2,%d1
	jeq .L147
	jcc .L153
	addq.l #1,20(%a0)
.L153:
	move.l 16(%sp),%a0
	move.b %d1,28(%a0,%d0.l)
.L147:
	movem.l (%sp),#28
	lea (12,%sp),%sp
	rts
.L156:
	moveq #1,%d4
	move.b %d4,29(%a0)
	move.l 16(%sp),%a0
	move.b %d1,28(%a0,%d0.l)
	jra .L147
	.size	pm_advance, .-pm_advance
	.align	2
	.globl	pm_lookup
	.type	pm_lookup, @function
pm_lookup:
	subq.l #8,%sp
	move.l %d2,-(%sp)
	moveq #15,%d2
	move.l 20(%sp),%d1
	move.l 16(%sp),%a1
	move.l 28(%sp),%a0
	move.l 24(%sp),8(%sp)
	cmp.l %d1,%d2
	jcs .L162
	tst.l 32(%sp)
	jeq .L159
	moveq #12,%d2
	muls.l %d1,%d2
	move.b 1(%a1,%d1.l),%d0
	move.l 24(%a1,%d2.l),%d2
	move.l %d2,4(%sp)
.L160:
	mvz.b %d0,%d0
	mov3q.l #5,%d2
	cmp.l %d0,%d2
	jcc .L161
	clr.l %d0
.L161:
	tst.l %a0
	jeq .L163
	moveq #12,%d2
	muls.l %d2,%d1
	move.l 4(%sp),32(%sp)
	move.l 8(%sp),28(%sp)
	lea 20(%a1,%d1.l),%a1
	move.l (%a1),24(%sp)
	move.l %a0,20(%sp)
	move.l %d0,16(%sp)
	move.l (%sp)+,%d2
	addq.l #8,%sp
	jra (pm_map.part.0)
.L159:
	move.l 24(%a1),%d2
	move.b (%a1),%d0
	move.l %d2,4(%sp)
	jra .L160
.L162:
	move.l 8(%sp),%d0
	move.l (%sp)+,%d2
	addq.l #8,%sp
	rts
.L163:
	move.l (%sp)+,%d2
	clr.l %d0
	addq.l #8,%sp
	rts
	.size	pm_lookup, .-pm_lookup
	.align	2
	.globl	pm_ui_step
	.type	pm_ui_step, @function
pm_ui_step:
	move.l %d2,-(%sp)
	move.l 16(%sp),%d1
	tst.l 20(%sp)
	jeq .L167
	moveq #15,%d0
	cmp.l 12(%sp),%d0
	jcs .L167
	move.l 12(%sp),%d0
	mov3q.l #1,%d2
	move.l 8(%sp),%a1
	lea 1(%a1,%d0.l),%a0
	mvz.b (%a0),%d0
	cmp.l %d0,%d2
	jeq .L169
.L192:
	mov3q.l #2,%d2
	cmp.l %d0,%d2
	jne .L190
	mov3q.l #2,%d0
	tst.l %d1
	jlt .L191
.L172:
	tst.l %d1
	sne %d1
	mvs.b %d1,%d1
	sub.l %d1,%d0
.L174:
	mov3q.l #5,%d1
	cmp.l %d0,%d1
	jge .L175
	mov3q.l #5,%d0
.L175:
	lea ORDER,%a1
	move.b (%a1,%d0.l),%d1
	move.b %d1,(%a0)
	mvz.b %d1,%d0
	move.l (%sp)+,%d2
	rts
.L167:
	move.l 8(%sp),%a0
	mov3q.l #1,%d2
	mvz.b (%a0),%d0
	cmp.l %d0,%d2
	jne .L192
.L169:
	clr.l %d0
	tst.l %d1
	jlt .L174
	sne %d1
	mov3q.l #1,%d0
	mvs.b %d1,%d1
	sub.l %d1,%d0
	jra .L174
.L190:
	mov3q.l #5,%d2
	cmp.l %d0,%d2
	jne .L193
	mov3q.l #3,%d0
	tst.l %d1
	jge .L172
	jra .L191
.L193:
	mov3q.l #3,%d2
	cmp.l %d0,%d2
	jne .L194
	mov3q.l #4,%d0
	tst.l %d1
	jge .L172
.L191:
	subq.l #1,%d0
	jra .L174
.L194:
	subq.l #4,%d0
	tst.l %d0
	jne .L195
	tst.l %d1
	jlt .L196
	sne %d1
	mov3q.l #5,%d0
	mvs.b %d1,%d1
	sub.l %d1,%d0
	jra .L174
.L196:
	mov3q.l #4,%d0
	jra .L174
.L195:
	tst.l %d1
	jge .L180
	clr.b %d1
	clr.l %d0
	move.b %d1,(%a0)
	move.l (%sp)+,%d2
	rts
.L180:
	tst.l %d1
	sne %d1
	clr.l %d0
	mvs.b %d1,%d1
	sub.l %d1,%d0
	jra .L174
	.size	pm_ui_step, .-pm_ui_step
	.section	.rodata.str1.1,"aMS",@progbits,1
.LC0:
	.string	"NORMAL"
	.text
	.align	2
	.globl	pm_ui_label
	.type	pm_ui_label, @function
pm_ui_label:
	move.l %a2,-(%sp)
	move.l 20(%sp),%a2
	tst.l 16(%sp)
	jeq .L198
	moveq #15,%d0
	cmp.l 12(%sp),%d0
	jcs .L198
	mov3q.l #7,%d1
	cmp.l 12(%sp),%d1
	jcs .L199
	moveq #84,%d0
	move.l 12(%sp),%d1
	add.l #49,%d1
	move.b %d1,1(%a2)
	move.l 8(%sp),%a1
	mov3q.l #3,%a0
	move.l 12(%sp),%d1
	move.b %d0,(%a2)
	moveq #32,%d0
	move.b %d0,2(%a2)
	mvz.b 1(%a1,%d1.l),%d0
.L201:
	mov3q.l #5,%d1
	cmp.l %d0,%d1
	jcs .L205
.L215:
	lea NAMES,%a1
	move.l (%a1,%d0.l*4),%a1
	move.b (%a1),%d1
	jeq .L203
	add.l %a2,%a0
.L204:
	move.b %d1,(%a0)
	move.l %a0,%d0
	addq.l #1,%a1
	addq.l #1,%a0
	move.b (%a1),%d1
	jne .L204
	mov3q.l #1,%a0
	sub.l %a2,%a0
	add.l %d0,%a0
.L203:
	clr.b %d0
	move.b %d0,(%a2,%a0.l)
	move.l %a2,%d0
	move.l (%sp)+,%a2
	rts
.L198:
	move.l 8(%sp),%a1
	mov3q.l #4,%a0
	move.l #1095519264,(%a2)
	mov3q.l #5,%d1
	mvz.b (%a1),%d0
	cmp.l %d0,%d1
	jcc .L215
.L205:
	moveq #78,%d1
	lea .LC0,%a1
	add.l %a2,%a0
	jra .L204
.L199:
	moveq #77,%d0
	mov3q.l #7,%d1
	and.l 12(%sp),%d1
	move.l 8(%sp),%a1
	mov3q.l #3,%a0
	move.b %d0,(%a2)
	moveq #32,%d0
	add.l #49,%d1
	move.b %d1,1(%a2)
	move.l 12(%sp),%d1
	move.b %d0,2(%a2)
	mvz.b 1(%a1,%d1.l),%d0
	jra .L201
	.size	pm_ui_label, .-pm_ui_label
	.align	2
	.globl	pm_per_track
	.type	pm_per_track, @function
pm_per_track:
	move.l %d2,-(%sp)
	move.l #635712,%d2
	move.b -2147457603,%d0
	mvz.b -2147457602,%d1
	mulu.w #36568,%d1
	mvz.b %d0,%d0
	muls.l %d2,%d0
	move.l (%sp)+,%d2
	move.l %d0,%a0
	add.l %d1,%a0
	mvz.w #36437,%d0
	add.l #1074668000,%a0
	tst.b (%a0,%d0.l)
	sne %d0
	mvs.b %d0,%d0
	neg.l %d0
	rts
	.size	pm_per_track, .-pm_per_track
	.align	2
	.globl	pm_track_length
	.type	pm_track_length, @function
pm_track_length:
	lea (-16,%sp),%sp
	movem.l #28,(%sp)
	move.l #635712,%d2
	move.l #36437,%a1
	move.b -2147457603,%d0
	mvz.b -2147457602,%d1
	mulu.w #36568,%d1
	mvz.b %d0,%d0
	muls.l %d2,%d0
	move.l %d0,%a0
	add.l %d1,%a0
	add.l #1074668000,%a0
	tst.b (%a0,%a1.l)
	jeq .L234
	move.l 20(%sp),%d0
	mov3q.l #7,%d4
	cmp.l 20(%sp),%d4
	jcs .L221
	mvz.w #2330,%d1
	muls.l %d1,%d0
	moveq #81,%d1
	lea (%a0,%d0.l),%a1
	move.b 80(%a1),%d0
.L222:
	move.b (%a1,%d1.l),%d1
	mvz.b %d0,%d0
	moveq #63,%d3
	move.b %d1,12(%sp)
	move.l %d0,%d1
	subq.l #1,%d1
	cmp.l %d1,%d3
	jcc .L223
	moveq #16,%d0
.L223:
	mvz.w #36432,%d1
	move.b (%a0,%d1.l),%d1
	move.w %d1,%a1
	mvz.w #36433,%d1
	mvz.b (%a0,%d1.l),%d1
	move.l %a1,%d4
	lsl.l #8,%d4
	or.l %d4,%d1
	tst.w %d1
	jle .L218
	move.l #36434,%a1
	mov3q.l #6,%d4
	mvz.b 12(%sp),%d2
	mvz.b (%a0,%a1.l),%d3
	move.l %d2,12(%sp)
	cmp.l %d3,%d4
	jcs .L229
	lea (ticks.0),%a1
	mvz.b (%a1,%d3.l),%d2
	mov3q.l #6,%d3
	move.l %d2,%a0
	move.w %a0,%d2
	mulu.w %d2,%d1
	cmp.l 12(%sp),%d3
	jcs .L230
.L235:
	move.l 12(%sp),%d4
	lea (ticks.0),%a0
	mvz.b (%a0,%d4.l),%d4
	move.l %d4,%a0
.L226:
	lea -1(%a0,%d1.l),%a1
	move.l %a0,%d3
	move.l %a1,%d2
	divu.l %d3,%d2
	cmp.l %d0,%d2
	jcc .L218
	cmp.l %a1,%a0
	jhi .L231
	move.l %d2,%d0
.L218:
	movem.l (%sp),#28
	lea (16,%sp),%sp
	rts
.L221:
	mvz.w #2224,%d2
	moveq #41,%d1
	muls.l %d2,%d0
	move.l %d0,%a1
	lea (848,%a1),%a1
	add.l %a0,%a1
	move.b 40(%a1),%d0
	jra .L222
.L234:
	mvz.w #36435,%d0
	moveq #63,%d3
	mvz.b (%a0,%d0.l),%d0
	move.l %d0,%d1
	subq.l #1,%d1
	cmp.l %d1,%d3
	jcc .L218
	movem.l (%sp),#28
	moveq #16,%d0
	lea (16,%sp),%sp
	rts
.L229:
	mov3q.l #6,%a0
	move.w %a0,%d2
	mov3q.l #6,%d3
	mulu.w %d2,%d1
	cmp.l 12(%sp),%d3
	jcc .L235
.L230:
	mov3q.l #6,%a0
	jra .L226
.L231:
	movem.l (%sp),#28
	mov3q.l #1,%d0
	lea (16,%sp),%sp
	rts
	.size	pm_track_length, .-pm_track_length
	.align	2
	.type	pm_effective_length, @function
pm_effective_length:
	move.l %d2,-(%sp)
	move.l 8(%sp),%d2
	move.l %d2,-(%sp)
	jsr pm_track_length
	addq.l #4,%sp
	moveq #15,%d1
	cmp.l %d2,%d1
	jcs .L236
	lea pm_comp,%a0
	mvz.b (%a0,%d2.l),%d1
	cmp.l %d1,%d0
	jeq .L238
	moveq #12,%d1
	move.b %d0,(%a0,%d2.l)
	muls.l %d2,%d1
	clr.w %d2
	lea pm_state,%a0
	move.w %d2,30(%a0,%d1.l)
.L236:
	move.l (%sp)+,%d2
	rts
.L238:
	moveq #12,%d1
	muls.l %d1,%d2
	move.l %d2,%a0
	add.l #pm_state,%a0
	move.b 30(%a0),%d1
	mvz.b 31(%a0),%d2
	tst.b %d1
	jeq .L244
	mvz.b %d1,%d0
.L244:
	cmp.l %d0,%d2
	jls .L236
	move.l %d2,%d0
	move.l (%sp)+,%d2
	rts
	.size	pm_effective_length, .-pm_effective_length
	.align	2
	.globl	pm_seq_step
	.type	pm_seq_step, @function
pm_seq_step:
	lea (-28,%sp),%sp
	movem.l #1084,(%sp)
	move.l 32(%sp),%d2
	mov3q.l #1,%d5
	jsr pm_ensure
	move.l -2147457608,%d0
	move.b -2147457603,%d4
	move.b -2147457602,%d1
	cmp.l %d0,%d5
	seq %d3
	move.b %d1,27(%sp)
	neg.l %d3
	tst.l pm_restart
	jne .L248
	cmp.l %d0,%d5
	jeq .L285
.L249:
	mvz.b %d4,%d0
	mvz.b pm_last_bank,%d1
	cmp.l %d0,%d1
	jeq .L286
.L248:
	pea pm_state
	clr.l pm_restart
	jsr pm_reset_all
	addq.l #4,%sp
.L250:
	move.l %d2,-(%sp)
	lea (31,%sp),%a0
	move.b %d3,pm_last_transport
	move.b %d4,pm_last_bank
	lea pm_effective_length,%a2
	move.b (%a0),pm_last_pattern
	jsr (%a2)
	addq.l #4,%sp
	moveq #15,%d0
	cmp.l %d2,%d0
	jcs .L287
	moveq #12,%d3
	moveq #63,%d4
	muls.l %d2,%d3
	lea pm_state,%a1
	cmp.l 36(%sp),%d4
	jcs .L253
	lea (%a1,%d3.l),%a0
	move.b 31(%a0),%d0
	tst.b 29(%a0)
	jeq .L254
	mvz.b 28(%a0),%d1
	cmp.l 36(%sp),%d1
	jls .L254
	tst.b %d0
	jeq .L280
	mvz.b 30(%a0),%d4
	mvz.b %d0,%d1
	cmp.l %d4,%d1
	jls .L280
	move.b %d0,30(%a0)
.L280:
	move.l 36(%sp),%d1
	addq.l #1,%d1
.L255:
	move.b %d1,31(%a1,%d3.l)
.L253:
	move.l %d2,-(%sp)
	move.l %a1,26(%sp)
	jsr (%a2)
	addq.l #4,%sp
	move.l 22(%sp),%a1
	tst.l %d0
	jeq .L259
.L257:
	cmp.l 36(%sp),%d0
	jhi .L259
	move.l 36(%sp),%d4
	lea (%a1,%d3.l),%a0
	remu.l %d0,%d1:%d4
	tst.b 29(%a0)
	jne .L260
.L288:
	moveq #1,%d5
	move.b %d5,29(%a0)
.L261:
	move.b %d1,28(%a1,%d3.l)
.L262:
	move.b -2147457603,%d1
	mvz.b -2147457602,%d4
	move.w %d4,%d5
	mvz.w #36437,%d4
	mvz.b %d1,%d1
	mulu.w #36568,%d5
	move.l %d5,%a0
	move.l #635712,%d5
	muls.l %d5,%d1
	add.l %d1,%a0
	add.l #1074668000,%a0
	tst.b (%a0,%d4.l)
	jeq .L263
	move.b 1(%a1,%d2.l),%d1
.L264:
	subq.l #1,%d1
	mvz.b %d1,%d1
	mov3q.l #4,%d4
	cmp.l %d1,%d4
	jcs .L252
	move.b -2147457603,%d1
	mvz.b -2147457602,%d5
	mvz.w #36437,%d4
	mulu.w #36568,%d5
	mvz.b %d1,%d1
	move.l %d5,%a0
	move.l #635712,%d5
	muls.l %d5,%d1
	add.l %d1,%a0
	add.l #1074668000,%a0
	tst.b (%a0,%d4.l)
	jeq .L267
	move.b 1(%a1,%d2.l),%d1
	move.l 24(%a1,%d3.l),%a0
.L268:
	mvz.b %d1,%d1
	mov3q.l #5,%d2
	cmp.l %d1,%d2
	jcc .L269
	clr.l %d1
.L269:
	tst.l %d0
	jeq .L247
	move.l %a0,-(%sp)
	move.l 40(%sp),-(%sp)
	move.l 20(%a1,%d3.l),-(%sp)
	move.l %d0,-(%sp)
	move.l %d1,-(%sp)
	jsr (pm_map.part.0)
	lea (20,%sp),%sp
.L247:
	movem.l (%sp),#1084
	lea (28,%sp),%sp
	rts
.L259:
	move.l 36(%sp),%d1
	lea (%a1,%d3.l),%a0
	tst.b 29(%a0)
	jeq .L288
.L260:
	mvz.b 28(%a0),%d4
	cmp.l %d4,%d1
	jeq .L262
	jcc .L261
	move.b %d1,28(%a1,%d3.l)
	addq.l #1,20(%a0)
	jra .L262
.L285:
	tst.b pm_last_transport.l
	jne .L249
	pea pm_state
	clr.l pm_restart
	jsr pm_reset_all
	addq.l #4,%sp
	jra .L250
.L254:
	mvz.b %d0,%d0
	move.l 36(%sp),%d1
	addq.l #1,%d1
	cmp.l %d1,%d0
	jcs .L255
	move.l %d2,-(%sp)
	move.l %a1,26(%sp)
	jsr (%a2)
	addq.l #4,%sp
	move.l 22(%sp),%a1
	tst.l %d0
	jne .L257
	jra .L259
.L287:
	move.l %d2,-(%sp)
	move.l #635712,%d2
	jsr (%a2)
	move.b -2147457603,%d0
	mvz.b -2147457602,%d1
	addq.l #4,%sp
	mulu.w #36568,%d1
	mvz.b %d0,%d0
	muls.l %d2,%d0
	move.l %d0,%a0
	add.l %d1,%a0
	mvz.w #36437,%d0
	add.l #1074668000,%a0
	move.b (%a0,%d0.l),%d0
.L252:
	movem.l (%sp),#1084
	move.l 36(%sp),%d0
	lea (28,%sp),%sp
	rts
.L263:
	move.b (%a1),%d1
	jra .L264
.L267:
	move.b (%a1),%d1
	move.l pm_state+24,%a0
	jra .L268
.L286:
	mvz.b 27(%sp),%d0
	mvz.b pm_last_pattern,%d1
	cmp.l %d0,%d1
	jeq .L250
	pea pm_state
	clr.l pm_restart
	jsr pm_reset_all
	addq.l #4,%sp
	jra .L250
	.size	pm_seq_step, .-pm_seq_step
	.align	2
	.globl	pm_seq_peek
	.type	pm_seq_peek, @function
pm_seq_peek:
	subq.l #4,%sp
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	jsr pm_ensure
	move.l 16(%sp),-(%sp)
	jsr pm_effective_length
	addq.l #4,%sp
	moveq #15,%d1
	cmp.l 16(%sp),%d1
	jcc .L310
	mov3q.l #1,%d3
	cmp.l -2147457608.l,%d3
	jne .L300
.L300:
	move.b -2147457603,%d0
	mvz.b -2147457602,%d1
	move.l #635712,%d2
	mulu.w #36568,%d1
	mvz.b %d0,%d0
	muls.l %d2,%d0
	move.l %d0,%a0
	add.l %d1,%a0
	mvz.w #36437,%d0
	add.l #1074668000,%a0
	move.b (%a0,%d0.l),%d0
.L294:
	move.l 20(%sp),%d0
.L289:
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L310:
	move.b -2147457603,%d1
	mvz.b -2147457602,%d2
	move.l #36437,%a1
	move.w %d2,%d3
	move.l #635712,%d2
	mvz.b %d1,%d1
	muls.l %d2,%d1
	mulu.w #36568,%d3
	move.l %d3,%a0
	add.l %d1,%a0
	add.l #1074668000,%a0
	tst.b (%a0,%a1.l)
	jeq .L291
	move.l 16(%sp),%d3
	mov3q.l #4,%d2
	lea pm_state,%a1
	move.b 1(%a1,%d3.l),%d1
	subq.l #1,%d1
	mvz.b %d1,%d1
	cmp.l %d1,%d2
	jcs .L294
.L293:
	mov3q.l #1,%d3
	cmp.l -2147457608.l,%d3
	jeq .L311
	move.b -2147457603,%d1
	mvz.b -2147457602,%d2
	move.w %d2,%d3
	move.l #635712,%d2
	mvz.b %d1,%d1
	muls.l %d2,%d1
	mulu.w #36568,%d3
	move.l %d3,%a0
	add.l %d1,%a0
	mvz.w #36437,%d1
	add.l #1074668000,%a0
	tst.b (%a0,%d1.l)
	sne %d1
	mvs.b %d1,%d1
	neg.l %d1
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	move.l 28(%sp),-(%sp)
	move.l 28(%sp),-(%sp)
	pea pm_state
	jsr (pm_lookup_next_run.part.0)
	lea (20,%sp),%sp
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L291:
	lea pm_state,%a1
	mov3q.l #4,%d2
	move.b (%a1),%d1
	subq.l #1,%d1
	mvz.b %d1,%d1
	cmp.l %d1,%d2
	jcc .L293
	jra .L294
.L311:
	move.b -2147457603,%d3
	mvz.b -2147457602,%d1
	mulu.w #36568,%d1
	mvz.b %d3,%d2
	move.l #635712,%d3
	muls.l %d3,%d2
	move.l %d2,%a0
	add.l %d1,%a0
	mvz.w #36437,%d1
	add.l #1074668000,%a0
	tst.b (%a0,%d1.l)
	jeq .L312
	move.l 16(%sp),%d3
	moveq #12,%d1
	move.l 16(%sp),%d2
	muls.l %d1,%d3
	move.b 1(%a1,%d2.l),%d1
	move.l 24(%a1,%d3.l),%a0
.L295:
	mvz.b %d1,%d1
	mov3q.l #5,%d3
	cmp.l %d1,%d3
	jcc .L296
	clr.l %d1
.L296:
	tst.l %d0
	jeq .L289
	move.l 16(%sp),%d2
	moveq #12,%d3
	move.l %a0,-(%sp)
	move.l 24(%sp),-(%sp)
	muls.l %d3,%d2
	move.l 20(%a1,%d2.l),-(%sp)
	move.l %d0,-(%sp)
	move.l %d1,-(%sp)
	jsr (pm_map.part.0)
	lea (20,%sp),%sp
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L312:
	move.b (%a1),%d1
	move.l pm_state+24,%a0
	jra .L295
	.size	pm_seq_peek, .-pm_seq_peek
	.align	2
	.globl	pm_show
	.type	pm_show, @function
pm_show:
	lea (-12,%sp),%sp
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	jsr pm_ensure
	mov3q.l #-1,%d0
	cmp.l 24(%sp),%d0
	jeq .L340
	moveq #15,%d3
	cmp.l 24(%sp),%d3
	jcs .L317
	move.b -2147457603,%d0
	mvz.b -2147457602,%d1
	move.l #635712,%d2
	move.l #36437,%a1
	mulu.w #36568,%d1
	mvz.b %d0,%d0
	muls.l %d2,%d0
	move.l %d0,%a0
	add.l %d1,%a0
	add.l #1074668000,%a0
	tst.b (%a0,%a1.l)
	jeq .L318
.L341:
	move.l 24(%sp),%d3
	lea pm_state,%a1
	move.b 1(%a1,%d3.l),%d0
.L319:
	subq.l #1,%d0
	mvz.b %d0,%d0
	mov3q.l #4,%d1
	cmp.l %d0,%d1
	jcs .L317
	move.l 24(%sp),-(%sp)
	move.l %a1,12(%sp)
	jsr pm_effective_length
	addq.l #4,%sp
	mov3q.l #1,%d2
	move.l 8(%sp),%a1
	cmp.l -2147457608.l,%d2
	jeq .L320
	move.b -2147457603,%d1
	mvz.b -2147457602,%d3
	move.w %d3,%d2
	move.l #635712,%d3
	mvz.b %d1,%d1
	muls.l %d3,%d1
	mulu.w #36568,%d2
	move.l %d2,%a0
	add.l %d1,%a0
	mvz.w #36437,%d1
	add.l #1074668000,%a0
	tst.b (%a0,%d1.l)
	sne %d1
	mvs.b %d1,%d1
	neg.l %d1
	tst.l %d0
	jeq .L321
	move.l 28(%sp),%d2
	remu.l %d0,%d3:%d2
	move.l %d3,28(%sp)
.L321:
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	move.l 36(%sp),-(%sp)
	move.l 36(%sp),-(%sp)
	pea pm_state
	jsr (pm_lookup_next_run.part.0)
	lea (20,%sp),%sp
.L313:
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	lea (12,%sp),%sp
	rts
.L317:
	move.l 28(%sp),%d0
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	lea (12,%sp),%sp
	rts
.L318:
	lea pm_state,%a1
	move.b (%a1),%d0
	jra .L319
.L340:
	move.b -2147457603,%d0
	mvz.b -2147457602,%d1
	move.l #635712,%d2
	move.l #36437,%a1
	mulu.w #36568,%d1
	mvz.b %d0,%d0
	muls.l %d2,%d0
	move.l %d0,%a0
	add.l %d1,%a0
	add.l #1074668000,%a0
	tst.b (%a0,%a1.l)
	jne .L317
	clr.l 24(%sp)
	move.l #635712,%d2
	move.b -2147457603,%d0
	mvz.b -2147457602,%d1
	move.l #36437,%a1
	mulu.w #36568,%d1
	mvz.b %d0,%d0
	muls.l %d2,%d0
	move.l %d0,%a0
	add.l %d1,%a0
	add.l #1074668000,%a0
	tst.b (%a0,%a1.l)
	jeq .L318
	jra .L341
.L320:
	move.l 24(%sp),%d1
	moveq #12,%d2
	muls.l %d2,%d1
	lea (%a1,%d1.l),%a0
	move.l 20(%a0),%d3
	move.l %d1,16(%sp)
	move.l %d3,12(%sp)
	tst.b 29(%a0)
	jeq .L324
	mvz.b 28(%a0),%d1
	cmp.l 28(%sp),%d1
	jcs .L342
.L324:
	move.b -2147457603,%d1
	mvz.b -2147457602,%d2
	move.w %d2,%d3
	move.l #635712,%d2
	mvz.b %d1,%d1
	muls.l %d2,%d1
	mulu.w #36568,%d3
	move.l %d3,%a0
	add.l %d1,%a0
	mvz.w #36437,%d3
	add.l #1074668000,%a0
	tst.b (%a0,%d3.l)
	jeq .L325
	tst.l %d0
	jeq .L313
	move.l 28(%sp),%d1
	move.l 24(%sp),%d3
	remu.l %d0,%d2:%d1
	mvz.b 1(%a1,%d3.l),%d1
	mov3q.l #5,%d3
	move.l %d2,%a0
	move.l 16(%sp),%d2
	move.l 24(%a1,%d2.l),%a1
	cmp.l %d1,%d3
	jcs .L331
.L327:
	move.l %a1,-(%sp)
	move.l %a0,-(%sp)
	move.l 20(%sp),-(%sp)
	move.l %d0,-(%sp)
	move.l %d1,-(%sp)
	jsr (pm_map.part.0)
	lea (20,%sp),%sp
.L343:
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	lea (12,%sp),%sp
	rts
.L325:
	tst.l %d0
	jeq .L313
	move.l 28(%sp),%d1
	mov3q.l #5,%d3
	remu.l %d0,%d2:%d1
	mvz.b (%a1),%d1
	move.l pm_state+24,%a1
	move.l %d2,%a0
	cmp.l %d1,%d3
	jcc .L327
.L331:
	move.l %a1,-(%sp)
	move.l %a0,-(%sp)
	move.l 20(%sp),-(%sp)
	move.l %d0,-(%sp)
	clr.l %d1
	move.l %d1,-(%sp)
	jsr (pm_map.part.0)
	lea (20,%sp),%sp
	jra .L343
.L342:
	tst.l %d3
	sne %d1
	mvs.b %d1,%d1
	add.l %d1,12(%sp)
	jra .L324
	.size	pm_show, .-pm_show
	.align	2
	.globl	pm_key_updown
	.type	pm_key_updown, @function
pm_key_updown:
	subq.l #4,%sp
	move.l %d2,-(%sp)
	move.l #635712,%d2
	jsr pm_ensure
	move.b -2147457603,%d0
	mvz.b -2147457602,%d1
	mulu.w #36568,%d1
	mvz.b %d0,%d0
	muls.l %d2,%d0
	move.l %d0,%a0
	add.l %d1,%a0
	mvz.w #36437,%d0
	add.l #1074668000,%a0
	tst.b (%a0,%d0.l)
	sne %d1
	mvs.b %d1,%d1
	neg.l %d1
	tst.l 16(%sp)
	jne .L351
	pea pm_toast
	move.l %d1,-(%sp)
	move.l 20(%sp),-(%sp)
	pea pm_state
	jsr pm_ui_label
	lea (16,%sp),%sp
	move.l (%sp)+,%d2
	addq.l #4,%sp
	rts
.L351:
	move.l %d1,-(%sp)
	move.l 20(%sp),-(%sp)
	move.l 20(%sp),-(%sp)
	pea pm_state
	move.l %d1,20(%sp)
	jsr pm_ui_step
	jsr pm_store_current
	lea (16,%sp),%sp
	move.l 4(%sp),%d1
	pea pm_toast
	move.l %d1,-(%sp)
	move.l 20(%sp),-(%sp)
	pea pm_state
	jsr pm_ui_label
	lea (16,%sp),%sp
	move.l (%sp)+,%d2
	addq.l #4,%sp
	rts
	.size	pm_key_updown, .-pm_key_updown
	.align	2
	.globl	pm_project_format
	.type	pm_project_format, @function
pm_project_format:
	lea (-20,%sp),%sp
	movem.l #3100,(%sp)
	move.l 28(%sp),%d2
	move.l 24(%sp),%a3
	jsr pm_ensure
	cmp.l #255,%d2
	jhi .L353
	mvz.w pm_cur,%d1
	move.l %d2,%d0
	addq.l #1,%d0
	cmp.l %d1,%d0
	jeq .L367
	move.l %d2,%d0
	lsl.l #4,%d0
	move.l %d0,%a0
	add.l %d2,%a0
	add.l #pm_table,%a0
	move.l %a0,%d3
	move.l %a0,%a1
	add.l #17,%d3
.L356:
	addq.l #1,%a1
	tst.b -1(%a1)
	jne .L355
	cmp.l %a1,%d3
	jne .L356
.L353:
	movem.l (%sp),#3100
	clr.l %d0
	lea (20,%sp),%sp
	rts
.L355:
	lea pm_key,%a1
	move.l %a3,%a2
.L358:
	move.b (%a1)+,(%a2)+
	cmp.l #pm_key+12,%a1
	jne .L358
	moveq #15,%d0
	and.l %d2,%d0
	moveq #58,%d1
	lsr.l #4,%d2
	lea (16,%a3),%a1
	add.l #65,%d2
	move.b %d2,12(%a3)
	moveq #10,%d2
	addq.l #1,%d0
	move.b %d1,15(%a3)
	remu.l %d2,%d1:%d0
	divu.l %d2,%d0
	add.l #48,%d0
	add.l #48,%d1
	move.b %d0,13(%a3)
	move.b %d1,14(%a3)
.L360:
	move.b (%a0)+,%d0
	moveq #48,%d1
	mov3q.l #5,%d4
	mvz.b %d0,%d2
	add.l #48,%d0
	cmp.l %d2,%d4
	jcs .L359
	move.b %d0,%d1
.L359:
	move.b %d1,(%a1)+
	cmp.l %a0,%d3
	jne .L360
	move.w #3338,%d0
	clr.b %d1
	move.w %d0,33(%a3)
	move.b %d1,35(%a3)
	moveq #35,%d0
	movem.l (%sp),#3100
	lea (20,%sp),%sp
	rts
.L367:
	jsr pm_store_current
	move.l %d2,%d0
	lsl.l #4,%d0
	move.l %d0,%a0
	add.l %d2,%a0
	add.l #pm_table,%a0
	move.l %a0,%d3
	move.l %a0,%a1
	add.l #17,%d3
	jra .L356
	.size	pm_project_format, .-pm_project_format
	.align	2
	.globl	pm_project_begin
	.type	pm_project_begin, @function
pm_project_begin:
	subq.l #4,%sp
	move.l 8(%sp),(%sp)
	jsr pm_ensure
	tst.l (%sp)
	jeq .L368
	move.l #pm_table+17,%d0
.L370:
	move.l %d0,%a0
	lea (-17,%a0),%a0
.L371:
	clr.b (%a0)+
	cmp.l %a0,%d0
	jne .L371
	move.l %a0,%d0
	add.l #17,%d0
	cmp.l #pm_table+4352,%a0
	jne .L370
	clr.w %d0
	move.w %d0,pm_cur
	addq.l #4,%sp
	jra pm_nv_store
.L368:
	addq.l #4,%sp
	rts
	.size	pm_project_begin, .-pm_project_begin
	.align	2
	.globl	pm_project_line
	.type	pm_project_line, @function
pm_project_line:
	lea (-28,%sp),%sp
	move.l %a6,-(%sp)
	move.l %d2,-(%sp)
	move.l 40(%sp),%a6
	move.l %a6,%a1
	lea pm_key,%a0
.L378:
	addq.l #1,%a1
	addq.l #1,%a0
	mvs.b -1(%a1),%d1
	mvs.b -1(%a0),%d0
	cmp.l %d1,%d0
	jne .L390
	cmp.l #pm_key+12,%a0
	jne .L378
	tst.l 44(%sp)
	jeq .L399
.L379:
	mov3q.l #1,%d0
.L376:
	move.l (%sp)+,%d2
	move.l (%sp)+,%a6
	lea (28,%sp),%sp
	rts
.L399:
	jsr pm_ensure
	move.b 12(%a6),%d0
	moveq #15,%d2
	add.l #-65,%d0
	mvz.b %d0,%d1
	cmp.l %d1,%d2
	jcs .L380
	mvz.b 13(%a6),%d1
	moveq #9,%d2
	add.l #-48,%d1
	cmp.l %d1,%d2
	jcs .L379
	mvz.b 14(%a6),%d2
	move.l %d2,%a0
	moveq #9,%d2
	lea (-48,%a0),%a0
	cmp.l %a0,%d2
	jcs .L379
	moveq #10,%d2
	muls.l %d2,%d1
	moveq #15,%d2
	add.l %d1,%a0
	move.l %a0,%d1
	subq.l #1,%d1
	cmp.l %d1,%d2
	jcs .L379
	mvs.b 15(%a6),%d1
	moveq #58,%d2
	cmp.l %d1,%d2
	jne .L379
	ext.w %d0
	lea (16,%a6),%a1
	lea (33,%a6),%a6
	mvz.w %d0,%d0
	lsl.l #4,%d0
	lea -1(%a0,%d0.l),%a0
	move.l %a0,10(%sp)
	move.w 12(%sp),%d0
	mulu.w #17,%d0
	move.l %d0,%a0
	add.l #pm_table,%a0
.L383:
	clr.b %d1
	move.b (%a1),%d0
	addq.l #1,%a1
	moveq #9,%d2
	move.b %d1,15(%sp)
	mvz.b %d0,%d1
	add.l #-48,%d0
	add.l #-48,%d1
	cmp.l %d1,%d2
	jcs .L381
	mov3q.l #5,%d2
	cmp.l %d1,%d2
	jcs .L382
	move.b %d0,15(%sp)
.L382:
	move.b 15(%sp),(%a0)+
	cmp.l %a1,%a6
	jne .L383
.L381:
	move.l 10(%sp),-(%sp)
	jsr pm_nv_row
	clr.w %d0
	addq.l #4,%sp
	move.w %d0,pm_cur
	mov3q.l #1,%d0
	jra .L376
.L390:
	move.l (%sp)+,%d2
	clr.l %d0
	move.l (%sp)+,%a6
	lea (28,%sp),%sp
	rts
.L380:
	clr.b %d1
	lea (12,%a6),%a0
	clr.l 19(%sp)
	clr.l 23(%sp)
	clr.l 27(%sp)
	clr.l 31(%sp)
	lea (36,%sp),%a6
	lea (19,%sp),%a1
	move.b %d1,35(%sp)
.L386:
	move.b (%a0),%d1
	clr.b %d2
	addq.l #1,%a0
	mvz.b %d1,%d0
	move.b %d2,10(%sp)
	add.l #-48,%d1
	moveq #9,%d2
	add.l #-48,%d0
	cmp.l %d0,%d2
	jcs .L384
	mov3q.l #5,%d2
	cmp.l %d0,%d2
	jcs .L385
	move.b %d1,10(%sp)
.L385:
	move.b 10(%sp),(%a1)+
	cmp.l %a1,%a6
	jne .L386
.L384:
	move.l #pm_table,%d0
.L387:
	move.l %d0,%a1
	lea (19,%sp),%a0
.L388:
	move.b (%a0)+,(%a1)+
	cmp.l %a0,%a6
	jne .L388
	add.l #17,%d0
	cmp.l #pm_table+4352,%d0
	jne .L387
	clr.w %d0
	move.w %d0,pm_cur
	jsr pm_nv_store
	mov3q.l #1,%d0
	jra .L376
	.size	pm_project_line, .-pm_project_line
	.align	2
	.globl	pm_pattern_copy
	.type	pm_pattern_copy, @function
pm_pattern_copy:
	mvz.w #36568,%d0
	subq.l #8,%sp
	move.l %d2,-(%sp)
	cmp.l 24(%sp),%d0
	jeq .L422
.L400:
	move.l (%sp)+,%d2
	addq.l #8,%sp
	rts
.L422:
	jsr pm_ensure
	move.l 20(%sp),-(%sp)
	lea pattern_row,%a1
	move.l %a1,12(%sp)
	jsr (%a1)
	addq.l #4,%sp
	move.l 8(%sp),%a1
	tst.l %d0
	jeq .L400
	move.l 16(%sp),-(%sp)
	move.l %d0,8(%sp)
	jsr (%a1)
	addq.l #4,%sp
	move.l 4(%sp),%a0
	tst.l %d0
	jeq .L400
	cmp.l %a0,%d0
	jeq .L400
	move.w pm_cur,%d1
	jeq .L402
	subq.l #1,%d1
	mulu.w #17,%d1
	add.l #pm_table,%d1
	cmp.l %a0,%d1
	jeq .L423
.L402:
	move.l %a0,%d1
	move.l %d0,%a1
	add.l #17,%d1
.L403:
	move.b (%a0)+,(%a1)+
	cmp.l %a0,%d1
	jne .L403
	cmp.l #pm_clip,%d0
	jeq .L400
	cmp.l #pm_undo,%d0
	jeq .L400
	moveq #17,%d2
	sub.l #pm_table,%d0
	divu.l %d2,%d0
	move.l %d0,-(%sp)
	jsr pm_nv_row
	clr.w %d0
	addq.l #4,%sp
	move.l (%sp)+,%d2
	move.w %d0,pm_cur
	addq.l #8,%sp
	rts
.L423:
	move.l %d0,8(%sp)
	move.l %a0,4(%sp)
	jsr pm_store_current
	move.l 4(%sp),%a0
	move.l %a0,%d1
	move.l 8(%sp),%d0
	add.l #17,%d1
	move.l %d0,%a1
	jra .L403
	.size	pm_pattern_copy, .-pm_pattern_copy
	.align	2
	.globl	pm_pattern_clear
	.type	pm_pattern_clear, @function
pm_pattern_clear:
	move.l %d2,-(%sp)
	jsr pm_ensure
	move.l 8(%sp),-(%sp)
	jsr pattern_row
	addq.l #4,%sp
	tst.l %d0
	jeq .L424
	cmp.l #pm_clip,%d0
	jeq .L424
	cmp.l #pm_undo,%d0
	jeq .L424
	move.l %d0,%d1
	move.l %d0,%a0
	add.l #17,%d1
.L426:
	clr.b (%a0)+
	cmp.l %a0,%d1
	jne .L426
	sub.l #pm_table,%d0
	moveq #17,%d2
	divu.l %d2,%d0
	move.l %d0,-(%sp)
	jsr pm_nv_row
	clr.w %d0
	addq.l #4,%sp
	move.w %d0,pm_cur
.L424:
	move.l (%sp)+,%d2
	rts
	.size	pm_pattern_clear, .-pm_pattern_clear
	.section	.rodata
	.type	ticks.0, @object
	.size	ticks.0, 7
ticks.0:
	.base64	"AwQGCAwYMA=="
	.type	pm_key, @object
	.size	pm_key, 13
pm_key:
	.string	"#PLAY_MODES="
	.type	ORDER, @object
	.size	ORDER, 6
ORDER:
	.base64	"AAECBQME"
	.section	.rodata.str1.1
.LC1:
	.string	"REVERSED"
.LC2:
	.string	"PINGPONG"
.LC3:
	.string	"RANDOM"
.LC4:
	.string	"SHUFFLE"
.LC5:
	.string	"PINGPONG 2"
	.section	.rodata
	.align	2
	.type	NAMES, @object
	.size	NAMES, 24
NAMES:
	.long	.LC0
	.long	.LC1
	.long	.LC2
	.long	.LC3
	.long	.LC4
	.long	.LC5

| ---- hooks.s ----
| PLAY MODES -- the hand-written part of the unit: the detour stubs, the
| register-saving entries they call, and the state the C keeps in
| loader-owned DRAM. generate.py appends this to the compiled playmode.c +
| adapter.c.
|
| Sites read from the owner's original 1.40C with investigate.py (rounds 1
| to 4, 3-7 Oct 2026); INVESTIGATION.md section 4 has the stock listings.
| Every stub is reached by a six-byte `jmp` that the manifest plants over
| whole stock instructions, replays them, and jumps back.
        .text
        .balign 4
        .global pm_step_entry, pm_peek_entry, pm_show_entry, pm_key_entry

| pm_step_entry(track, raw) -> d0 = the step to play.
| Saves everything the C may clobber except d0, so a stub can call it in
| the middle of stock code: push raw, push track, jsr, addq #8,sp.
pm_step_entry:
        lea     -12(%sp),%sp
        movem.l %d1/%a0-%a1,(%sp)
        move.l  20(%sp),-(%sp)          | raw
        move.l  20(%sp),-(%sp)          | track (shifted by the first push)
        jsr     pm_seq_step
        addq.l  #8,%sp
        movem.l (%sp),%d1/%a0-%a1
        lea     12(%sp),%sp
        rts

| pm_peek_entry(track, raw) -> d0: the look-ahead form, no state change.
pm_peek_entry:
        lea     -12(%sp),%sp
        movem.l %d1/%a0-%a1,(%sp)
        move.l  20(%sp),-(%sp)
        move.l  20(%sp),-(%sp)
        jsr     pm_seq_peek
        addq.l  #8,%sp
        movem.l (%sp),%d1/%a0-%a1
        lea     12(%sp),%sp
        rts

| pm_show_entry(track, raw) -> d0: the step the display should show.
pm_show_entry:
        lea     -12(%sp),%sp
        movem.l %d1/%a0-%a1,(%sp)
        move.l  20(%sp),-(%sp)
        move.l  20(%sp),-(%sp)
        jsr     pm_show
        addq.l  #8,%sp
        movem.l (%sp),%d1/%a0-%a1
        lea     12(%sp),%sp
        rts

| pm_key_entry(track, delta): TRACK held + UP (-1) / DOWN (+1). Changes the
| mode and opens the stock toast with the new text. Key-handler context
| ONLY: the toast's close path reaches the kernel post 0x40000c3c, which
| hard-crashed a unit when reached from the frame path (Kyoti, Session 93).
| The duration must be > 0 (0 or less hung a unit: Kyoti, Session 50).
        .equ    NOTIFY, 0x4005a2b8      | FUN_4005a2b8(text, duration)
        .equ    REBUILD, 0x4009da20     | the working-set rebuild an edit calls; -1 = all tracks
        .equ    TOAST_TIME, 0x3c        | 1 s at the 60 Hz UI tick
pm_key_entry:
        lea     -16(%sp),%sp
        movem.l %d0-%d1/%a0-%a1,(%sp)
        move.l  24(%sp),-(%sp)          | delta
        move.l  24(%sp),-(%sp)          | track
        jsr     pm_key_updown           | fills pm_toast
        addq.l  #8,%sp
        pea     TOAST_TIME
        pea     pm_toast
        jsr     NOTIFY
        addq.l  #8,%sp
        pea     0xffffffff              | re-prepare every track's step in the
        jsr     REBUILD                 | new mode, as stock does after an edit
        addq.l  #4,%sp
        movem.l (%sp),%d0-%d1/%a0-%a1
        lea     16(%sp),%sp
        rts

| ---- the detour stubs ------------------------------------------------------
        .global pm_audio_step, pm_midi_step, pm_audio_rebuild, pm_midi_rebuild
        .global pm_arrow_key, pm_track_key, pm_step_getter
        .global pm_start_play, pm_start_ext1, pm_start_ext2, pm_start_ext3

| 0x400a2d6a, the tick's audio pass, just before 0x4009d1e8(track, bank,
| pattern, step, n): stock loads step = 0x800064d0[track] (track in d5).
| Displaced: lea 0x800064d0,%a0 (6). The next instruction, mvzb
| (0,%a0,%d5.l),%d0, is done here and skipped on the way back.
pm_audio_step:
        lea     0x800064d0,%a0
        mvz.b   %a0@(0,%d5:l),%d0         | MIT syntax, as objdump prints it
        move.l  %d0,-(%sp)              | raw step
        move.l  %d5,-(%sp)              | track 0..7
        jsr     pm_step_entry           | d0 := the step to play; d1/a0/a1 kept
        addq.l  #8,%sp
        jmp     0x400a2d74              | movel %d0,%sp@- (the step argument)

| 0x400a39b6, the tick's MIDI pass, before 0x4009cf4c(track, bank, pattern,
| step, n): step = 0x800064d0[8 + track] via the walking pointer at
| 100(%sp); MIDI track in d7. Displaced (8, the manifest pads one nop):
| moveal %sp@(100),%a0 ; mvzb %a0@(8),%d0. A jmp leaves sp as stock had it.
pm_midi_step:
        movea.l 100(%sp),%a0
        mvz.b   8(%a0),%d0
        move.l  %d0,-(%sp)
        move.l  %d7,%d1
        addq.l  #8,%d1                  | the engine's MIDI tracks are 8..15
        move.l  %d1,-(%sp)
        jsr     pm_step_entry
        addq.l  #8,%sp
        jmp     0x400a39be              | movel %d0,%sp@-

| 0x4009dc86 / 0x4009e3dc, the working-set rebuild 0x4009da20 (after an
| edit): stock computes the current step in d2 and calls the step handler
| with n = -1. Track in d6 (0..7 audio; 8..15 on the MIDI branch, which
| 0x4009dc78 takes when d6 > 7). Displaced: pea 0xffffffff ; movel %d2,
| %sp@- (6). The look-ahead form: no engine state changes.
pm_audio_rebuild:
        pea     0xffffffff
        move.l  %d2,-(%sp)
        move.l  %d6,-(%sp)
        jsr     pm_peek_entry
        addq.l  #8,%sp
        move.l  %d0,-(%sp)
        jmp     0x4009dc8c

pm_midi_rebuild:
        pea     0xffffffff
        move.l  %d2,-(%sp)
        move.l  %d6,-(%sp)
        jsr     pm_peek_entry
        addq.l  #8,%sp
        move.l  %d0,-(%sp)
        jmp     0x4009e3e2

| 0x4009b2b0, stock step(track): track < 0 returns the master step
| (0x800065b4); otherwise it branches to 0x4009b2be for the track's own
| step. Its 11 callers are UI code: the trig LEDs, live recording, lock
| editing (track = the current track, MIDI tracks as 8 + t; -1 for the
| master). Both answers are mapped like the step that plays (the master
| only under NORMAL scale mode). Displaced: movel %sp@(4),%d0 ;
| bges 0x4009b2be (6).
pm_step_getter:
        move.l  4(%sp),%d0
        bge.s   .Lgetter_track
        mvz.w   0x800065b4,%d0          | stock: the master step
        move.l  %d0,-(%sp)              | raw
        pea     0xffffffff              | "track" -1: the master
        jsr     pm_show_entry           | mapped under NORMAL scale mode
        addq.l  #8,%sp
        rts
.Lgetter_track:
        move.l  %d0,-(%sp)              | call the stock per-track branch as
        jsr     0x4009b2be              | stock enters it: d0 = track, arg at 4(sp)
        addq.l  #4,%sp
        move.l  %d0,-(%sp)              | raw step
        move.l  8(%sp),-(%sp)           | track (the caller's argument)
        jsr     pm_show_entry
        addq.l  #8,%sp
        rts

| The four places that set the transport playing (0x800065b8 := 1), each
| followed by the same `lea 0x4610757c,%a0` (6), displaced here: PLAY
| 0x4009c3da (EUCLID's PLAY stub returns to this very address, so the two
| compose), and 0x400a2210 / 0x400a24d6 / 0x400a27e8 in the tick (external
| start / continue). Raise pm_restart. Only a0 is used (the displaced lea
| loads it next); data registers stay as stock left them (d0/d1/d5 hold the
| 1 just stored), and the next stock instruction sets the condition codes.
pm_start_play:
        lea     pm_restart,%a0
        move.l  #1,(%a0)                | no data register touched
        lea     0x4610757c,%a0
        jmp     0x4009c3e0
pm_start_ext1:
        lea     pm_restart,%a0
        move.l  #1,(%a0)                | no data register touched
        lea     0x4610757c,%a0
        jmp     0x400a2216
pm_start_ext2:
        lea     pm_restart,%a0
        move.l  #1,(%a0)                | no data register touched
        lea     0x4610757c,%a0
        jmp     0x400a24dc
pm_start_ext3:
        lea     pm_restart,%a0
        move.l  #1,(%a0)                | no data register touched
        lea     0x4610757c,%a0
        jmp     0x400a27ee

| 0x40040250, the TRACK key handler (codes 0x10..0x17), handler(code,
| event): event 1 = press, 0 = release (as the REC handler 0x40048774 reads
| it), other values (hold, repeat) leave the state alone. Stock has no plain
| "TRACK held" byte: 0x400c0aac is its double-tap memory and survives the
| release. So the held key is kept here, as track + 1 (0 = none, which is
| also what the zeroed DRAM starts with). Displaced: movel %d2,%sp@- ;
| movel %sp@(8),%d1 (6). d0 is free: stock loads it next.
pm_track_key:
        move.l  4(%sp),%d1
        subi.l  #0x0f,%d1               | code 0x10..0x17 -> 1..8
        beq.s   .Ltrack_stock
        moveq   #8,%d0
        cmp.l   %d0,%d1
        bhi.s   .Ltrack_stock           | unsigned: not a TRACK key
        move.l  8(%sp),%d0
        cmpi.l  #1,%d0
        bne.s   .Ltrack_other
        move.l  %d1,pm_held_track       | press
        bra.s   .Ltrack_stock
.Ltrack_other:
        tst.l   %d0
        bne.s   .Ltrack_stock           | hold / repeat: keep
        cmp.l   pm_held_track,%d1       | release of the held key
        bne.s   .Ltrack_stock
        clr.l   pm_held_track
.Ltrack_stock:
        move.l  %d2,-(%sp)              | displaced
        move.l  8(%sp),%d1              | displaced
        jmp     0x40040256

| 0x400491a0, the UP / DOWN handler (key codes 0x33 / 0x20), handler(code,
| event). Stock acts on the main screen only inside the arranger or one
| mode check; otherwise it returns. With a TRACK key held (pm_held_track) a
| press changes the play mode and is consumed. MIDI mode (0x80000012 != 0)
| addresses M1..M8.
| ASSUMED, to confirm on the unit: 0x33 is UP (towards NORMAL). If the
| toast walks the wrong way, change KEY_UP to 0x20.
        .equ    KEY_UP, 0x33
        .equ    MIDI_MODE, 0x80000012
pm_arrow_key:
        move.l  8(%sp),%d0              | ColdFire cmpi takes a data register only
        cmpi.l  #1,%d0                  | a press?
        bne.s   .Larrow_stock
        move.l  pm_held_track,%d0       | 1..8, 0 = none
        beq.s   .Larrow_stock
        subq.l  #1,%d0
        tst.l   MIDI_MODE
        beq.s   .Larrow_audio
        addq.l  #8,%d0
.Larrow_audio:
        moveq   #1,%d1                  | DOWN: towards SHUFFLE
        move.l  4(%sp),%a0
        cmpa.l  #KEY_UP,%a0
        bne.s   .Larrow_delta
        moveq   #-1,%d1                 | UP: towards NORMAL
.Larrow_delta:
        move.l  %d1,-(%sp)
        move.l  %d0,-(%sp)
        jsr     pm_key_entry            | change the mode, open the toast
        addq.l  #8,%sp
        rts                             | consumed: back to the key dispatcher
.Larrow_stock:
        move.l  %d2,-(%sp)              | displaced
        movea.l 8(%sp),%a0              | displaced
        jmp     0x400491a6

| ---- the project file ------------------------------------------------------
| The loader 0x400866c4(file, storing) reads project.work line by line and
| skips any line that starts with '#' (stock too); the writer 0x400882a2
| prints one "KEY=%d\r\n" line per setting. SCALE QUANTIZER plants its
| stubs on the instructions just before these three and returns to exactly
| these addresses, so the two compose (its lines are handled first; every
| other '#' line reaches ours). Investigation round 4.
        .global pm_proj_begin, pm_proj_line, pm_proj_write
        .equ    WRITE, 0x400166b8       | write(file, buffer, length), as the writer's a2

| 0x400866d4, the loader's head: d0 = its second argument (0 = the
| parse-only pass). Displaced: movel %d0,%sp@(1158) ; seq %d0 (6); the move
| sets Z for the seq. d1/a0/a1 are free here (reloaded before any use).
pm_proj_begin:
        move.l  %d0,-(%sp)
        jsr     pm_project_begin        | (storing): a storing pass starts NORMAL
        move.l  (%sp)+,%d0
        move.l  %d0,1158(%sp)           | displaced
        seq     %d0                     | displaced
        jmp     0x400866da

| 0x400867aa, the loader's comment check: d0 = the line's first character,
| d5 = '#', d3 = the line (NUL-ended, without CR LF). Displaced: cmpl
| %d0,%d5 ; beqw 0x40088224 (6). A '#' line goes to pm_project_line with the
| loader's parse-only flag (58(sp), nonzero on the parse-only pass) and is
| then skipped as stock skips it; d0/d1/a0/a1 are reloaded at the next line.
pm_proj_line:
        cmp.l   %d0,%d5
        beq.s   .Lline_hash
        jmp     0x400867b0              | not a comment: stock goes on
.Lline_hash:
        move.l  58(%sp),-(%sp)          | parse-only
        move.l  %d3,-(%sp)              | the line
        jsr     pm_project_line
        addq.l  #8,%sp
        jmp     0x40088224              | the loop's next line

| 0x400888b2, the writer, at PATTERN_CHANGE_AUTO_SILENCE_TRACKS's line: its
| value is already pushed (0x400888b0). d3 = the file. Our lines first (one
| per pattern with a mode other than NORMAL), then the displaced pea
| 0x400b8244 (6). d0/d1/a0/a1 are free (the stock line reloads them; its
| value is on the stack); d2 is the stock line's buffer, so it is kept. A
| failed write is not checked here; the stock line that follows checks its
| own.
pm_proj_write:
        move.l  %d2,-(%sp)
        moveq   #0,%d2                  | pattern index 0..255
.Lwrite_next:
        move.l  %d2,-(%sp)
        pea     pm_line
        jsr     pm_project_format       | d0 := the length, 0 = no line
        addq.l  #8,%sp
        tst.l   %d0
        beq.s   .Lwrite_skip
        move.l  %d0,-(%sp)
        pea     pm_line
        move.l  %d3,-(%sp)
        jsr     WRITE
        lea     12(%sp),%sp
.Lwrite_skip:
        addq.l  #1,%d2
        cmpi.l  #256,%d2
        bne.s   .Lwrite_next
        move.l  (%sp)+,%d2
        pea     0x400b8244              | displaced
        jmp     0x400888b8

| ---- pattern copy, paste and undo -----------------------------------------
| memcpy(dst, src, n) at the stock sites that move whole patterns between
| the bank RAM, the clipboard and the undo buffer (PLOCKS P2 found them):
| jsr sites call this instead of 0x40020898, lea sites load it into the
| register that their two jsr calls use. pm_pattern_copy moves the
| pattern's modes along; then the stock memcpy runs in the caller's frame
| as it was. memcpy may clobber d0/d1/a0/a1, so the C call may too.
        .global pm_memcpy
        .equ    MEMCPY, 0x40020898
pm_memcpy:
        move.l  12(%sp),-(%sp)          | n
        move.l  12(%sp),-(%sp)          | src (shifted by one push)
        move.l  12(%sp),-(%sp)          | dst (shifted by two)
        jsr     pm_pattern_copy
        lea     12(%sp),%sp
        jmp     MEMCPY

| 0x4003a39c, the end of stock's clear-pattern loop (every track of the
| pattern at [0x46c82456] + d6 reset to length 16 / scale 1X): the
| pattern's modes go back to NORMAL. Displaced: jsr %pc@(0x400339d8) (4,
| PC-relative, replayed absolute) ; moveq #-1,%d0 (2). d0/d1/a0/a1 are free
| (the call that follows clobbers them).
        .global pm_clear_pattern
pm_clear_pattern:
        move.l  0x46c82456,%d0          | the bank's RAM
        add.l   %d6,%d0                 | + the pattern's offset
        move.l  %d0,-(%sp)
        jsr     pm_pattern_clear
        addq.l  #4,%sp
        jsr     0x400339d8              | displaced
        moveq   #-1,%d0                 | displaced
        jmp     0x4003a3a2

| Explicitly initialised, loader-owned DRAM (as EUCLID's state), not the
| 0x80006a40 scratch block, which the live DSP path overwrites. The C's
| _Static_asserts pin the sizes.
        .balign 4
        .global pm_state, pm_ready, pm_last_transport, pm_last_bank
        .global pm_last_pattern, pm_toast, pm_held_track, pm_restart, pm_line
        .global pm_table, pm_cur, pm_clip, pm_undo, pm_comp
pm_state:
        .zero   224
pm_ready:
        .byte   0
pm_last_transport:
        .byte   0
pm_last_bank:
        .byte   0
pm_last_pattern:
        .byte   0
pm_toast:
        .zero   16
pm_held_track:
        .long   0                       | the held TRACK key + 1, 0 = none
pm_restart:
        .long   0                       | 1 = a transport start since the last step
pm_line:
        .zero   40                      | a project line: 12 + 4 + 17 + CR LF + NUL
pm_cur:
        .short  0                       | the row in pm_state.settings + 1, 0 = none
        .balign 4
pm_table:
        .zero   4352                    | 256 patterns x 17 modes (bank * 16 + pattern)
pm_clip:
        .zero   17                      | the modes of the pattern in stock's clipboard
pm_undo:
        .zero   17                      | ... and in its undo buffer
        .balign 4
pm_comp:
        .zero   16                      | per track: the computed length last seen
